on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build DnDGMod
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          dndgmod
          poetry.lock
          pyproject.toml
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
    - name: Install Poetry
      run: python.exe -m pip install poetry
    - name: Install Poetry-PyInstaller-Plugin
      run: python.exe -m poetry self add poetry-pyinstaller-plugin
    - name: Build DnDGMod with Poetry
      run: python.exe -m poetry build
    - name: Archive Wheel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dndgmod-distribution-artifacts
        path: dist
    - name: Archive Executable Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dndgmod-onefile-bundled
        path: dist/pyinstaller/win_amd64/dndgmod-onefile-bundled.exe
